steps:
  # 1. 執行 Docker 建構，現在 Dockerfile 就在根目錄
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'asia-east2-docker.pkg.dev/plucky-ripsaw-434010-b9/cloud-run-source-deploy/king-bei-ppdata/ppocr:latest',
      '-f', 'Dockerfile',
      '.'
    ]

  # 2. 將映像檔推送到 Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east2-docker.pkg.dev/plucky-ripsaw-434010-b9/cloud-run-source-deploy/king-bei-ppdata/ppocr:latest']

  # 3. 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'ppocr',
      '--image', 'asia-east2-docker.pkg.dev/plucky-ripsaw-434010-b9/cloud-run-source-deploy/king-bei-ppdata/ppocr:latest',
      '--region', 'asia-east2',
      '--platform', 'managed',
      '--port', '5002',
      '--allow-unauthenticated'
    ]

images:
  - 'asia-east2-docker.pkg.dev/plucky-ripsaw-434010-b9/cloud-run-source-deploy/king-bei-ppdata/ppocr:latest'
